### ISSUE TITLE
Current code throws IndexError

### ISSUE THREAD

**Issue by btemperton** [jessieren/VirHostMatcher#2]
Trying to run the toy test example results in the following error:

` python vhm.py -v test/toyexample/virus -b test/toyexample/host -t test/toyexample/hostTaxa.txt -o ~/output

Traceback (most recent call last):
  File "/users/PAS1117/osu8359/tools/VirHostMatcher/vhm.py", line 236, in <module>
    hostTaxaTable[hostTaxaTable=='']='unknown'
IndexError: in the future, 0-d boolean arrays will be interpreted as a valid boolean index`

Run using python 3.5.2, following a successful make.

**Comment by jessieren** [comment]
Hi Ben,

Thank you very much for reporting the error.

I guess it is the problem of the inconsistency of the string types between
python 2 and python 3.

Could you please try the new script attached and see if the error occurs
again?

I tested the code on python 2.7 and 3.6, it works. If it does not work,
could you please send me the screen output for diagnostics?

Thank you a lot.

Best,
Jessie

On Tue, Jan 16, 2018 at 10:58 PM, Ben Temperton <notifications@github.com>
wrote:

> Trying to run the toy test example results in the following error:
>
> ` python vhm.py -v test/toyexample/virus -b test/toyexample/host -t
> test/toyexample/hostTaxa.txt -o ~/output
>
> Traceback (most recent call last):
> File "/users/PAS1117/osu8359/tools/VirHostMatcher/vhm.py", line 236, in
> hostTaxaTable[hostTaxaTable=='']='unknown'
> IndexError: in the future, 0-d boolean arrays will be interpreted as a
> valid boolean index`
>
> Run using python 3.5.2, following a successful make.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jessieren_VirHostMatcher_issues_2&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=irWyXBTJAqCxHN7GNey4-g&m=i0C4w6hvHE3RnT8K0Bhu6qniC_x6bwz3O_vnjCa7bbc&s=YpRSJD1P9GIrOdPjAuqW8aJNWoCNRpmcadZ5_-JxK-E&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHgpvCNMjLFEuJ1ISkSeyZRX6RaxmjIVks5tLLkdgaJpZM4Rf5xn&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=irWyXBTJAqCxHN7GNey4-g&m=i0C4w6hvHE3RnT8K0Bhu6qniC_x6bwz3O_vnjCa7bbc&s=2dBMyUazjB-aNTaG9Cu97wnj_Zz1QH3nX0NaUdiwtPQ&e=>
> .
>



-- 
Jie Jessie Ren
Postdoc in Computational Biology and Bioinformatics
University of Southern California
1050 Childs Way, RRI 201

**Comment by jessieren** [comment]
Sorry I realized that the attached file in the email cannot present here. I just updated the vhm.py file in the github page. Could you please download the new script and see if it works?

Thanks!

**Comment by btemperton** [comment]
Hi Jessie,

Many thanks for the rapid response! The fix you pushed to vhm.py has fixed the problem.

Best wishes,
Ben

**Comment by jessieren** [comment]
Great to know!
